version: '3.8'

services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: loja_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loja_online_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # LocalStack (Simula S3)
  localstack:
    image: localstack/localstack
    container_name: loja_localstack
    ports:
      - "4566:4566"            
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "./localstack_data:/var/lib/localstack"
      - "./scripts/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh"

volumes:
  pgdata: